/*(1) The opposite of a number is the number itself with its sign reversed. 
For example, the opposite of 1 is -1. The opposite of -6 is 6.
 Write some code that assigns a numerical value to a variable, and prints out the opposite of that number.

*/
let reverse=function(num){
    let x=num;
    return -x;
}
console.log(reverse(-4))
/*

(2) The Fibonacci sequence starts with the values 0, 1. 
The next number in the sequence is generated by summing the previous 2 values, 
so the first 6 numbers in the sequence are: 0, 1, 1, 2, 3, 5.

(a) Write some code to print out the first 25 values in the Fibonacci sequence;

(b) Write some code to add up only the even values in the first 42 values of the Fibonacci sequence.
*/
function fib(n){
    let n1=0;
    let n2=1;
    console.log(n1)
    console.log(n2)
    for (let i=3;i<=n;i++){
        let n=n1+n2;
        console.log(n);
        n1=n2;
        n2=n;
    }
}

/*


(3) The sum of digits of a number is found by adding all the digits of a number together. 
For example, the sum of digits of 234 is 2 + 3 + 4 = 9.
 Write some code to take a numerical value and print out the sum of digits of that number.
*/
function sum(num){
    let sum=0;
    while (num>0){
        sum+=num%10;
        num=Math.floor(num/10);
    }
    console.log(sum);
}
sum(23)
/*


(4) Write some JavaScript to convert any number of days, hours, minutes and seconds into seconds.



(5) Given an array of numbers and a number k, write a JavaScript program to check whether the sum of any two numbers from the list is equal to k or not. For example, given [1, 5, 11, 5] and k = 16, your program should return "true", since 11 + 5 is 16.



(6) Write a JavaScript program to multiply all the items in an array by a single, specific value.



(7) Write a function which accepts a String as input, and returns true if that String is a palindrome, false if not (a palindrome is a word that is spelt the same backwards and forwards).



(8) Write a function which models basic population growth to see how long it will take a town of a certain size to reach a target population. It has a number of parameters:

- The starting population;

- The natural percentage increase each year;

- The number of people who move to the town each year;

- The target population.

The function should use the first three parameters to calculate and return the number of years before the population hits the specified target.
*/